//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StroyCompany.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public Nullable<byte> IsCompl { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TypeOreder TypeOreder { get; set; }
    }
}
